spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        # show_sql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  sql:
    init:
      mode: always
      schema-locations:
        - "classpath:sql/schema.sql"
      data-locations:
        - "classpath:sql/data.sql"

  ldap:
    embedded:
      ldif: classpath:ldap/ldap.ldif
      base-dn:
        - "dc=springframework,dc=org"
      port: 33389

logging:
  level:
    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE
