drop table if exists users CASCADE;

drop table if exists authorities CASCADE;

create table authorities (
    id bigint generated by default as identity,
    username varchar(255) not null,
    authority varchar(20) not null
);

CREATE TABLE IF NOT EXISTS users (
   id bigint generated by default as identity,
   password varchar(255),
   username varchar(255),
   enabled INT not null
);
